# Generated by Django 5.1.3 on 2024-12-22 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('max_participants', models.IntegerField(default=4)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('left_player', models.IntegerField(null=True)),
                ('right_player', models.IntegerField(null=True)),
                ('winner', models.IntegerField(null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Start'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'user_id')},
            },
        ),
    ]
