# Generated by Django 5.1.4 on 2024-12-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player', models.IntegerField(null=True)),
                ('right_player', models.IntegerField(null=True)),
                ('left_score', models.IntegerField(default=0)),
                ('right_score', models.IntegerField(default=0)),
                ('winner', models.IntegerField(null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Start'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('match_number', models.IntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
