# Generated by Django 5.1.4 on 2024-12-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_rename_parent_match_player_slot_tournamentmatch_parent_match_player_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentmatch',
            old_name='left_score',
            new_name='left_player_score',
        ),
        migrations.RenameField(
            model_name='tournamentmatch',
            old_name='right_score',
            new_name='right_player_score',
        ),
    ]
