# Generated by Django 5.1.4 on 2024-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_player', models.IntegerField(null=True)),
                ('right_player', models.IntegerField(null=True)),
                ('left_score', models.IntegerField(default=0)),
                ('right_score', models.IntegerField(default=0)),
                ('winner', models.IntegerField(null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Start'), ('started', 'Started'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
