# Generated by Django 5.1.4 on 2024-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalmatch',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready to Start'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
