# Generated by Django 5.1.4 on 2024-12-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_normalmatch_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalmatch',
            name='reception_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
