# Generated by Django 5.1.3 on 2024-12-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reception',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
