# Generated by Django 5.1.4 on 2024-12-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_reception_name_alter_reception_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='creator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
