# Generated by Django 5.1.4 on 2024-12-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_reception_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress')], default='waiting', max_length=20),
        ),
    ]
